update yml file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,16 +1,27 @@
-name: "Check Logs"
-description: "An action to check console statements in code"
+name: Check for console.log
 
-runs:
-  using: "node12" # or specify any supported environment
-  main: |
-    #!/bin/bash
-    set -e
+on:
+  pull_request:
+    types: [opened, reopened, synchronize]
 
-    # Search for console.log statements in changed files
-    if git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | xargs grep -En '\bconsole\.log\b'; then
-      echo "ERROR: Console.log statements found. Please remove them before merging the pull request."
-      exit 1
-    else
-      echo "No console.log statements found. Proceeding with the pull request."
-    fi
+jobs:
+  check_console_log:
+    name: Check for console.log statements
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Check for console.log
+        run: |
+          #!/bin/bash
+          set -e
+
+          # Search for console.log statements in changed files
+          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | xargs grep -En '\bconsole\.log\b'; then
+            echo "ERROR: Console.log statements found. Please remove them before merging the pull request."
+            exit 1
+          else
+            echo "No console.log statements found. Proceeding with the pull request."
+          fi
