update yml file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,9 +17,9 @@ runs:
         set -e
 
         # Search for console.log statements in changed files
-        if git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | xargs grep -En '\bconsole\.log\b'; then
-          echo "ERROR: Console.log statements found. Please remove them before merging the pull request."
-          exit 1
-        else
-          echo "No console.log statements found. Proceeding with the pull request."
-        fi
+        if grep -r --exclude=*.{js,json,yml,yaml} 'console.log' .; then
+            echo "ERROR: Console.log statements found. Please remove them before merging the pull request."
+            exit 1
+          else
+            echo "No console.log statements found. Proceeding with the pull request."
+          fi
